# Generated by Django 5.1.3 on 2024-11-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0002_alter_car_table_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=50)),
                ('building', models.CharField(max_length=5)),
                ('zip_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
    ]
