# Generated by Django 5.1.3 on 2024-11-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0003_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'additional_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booking_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_number', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'booking_services',
                'managed': False,
            },
        ),
    ]
