# Generated by Django 5.1.3 on 2024-11-30 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0004_additional_services_booking_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo_Code',
            fields=[
                ('promo_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'promo_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rental_Agreement',
            fields=[
                ('rental_agreement_id', models.AutoField(primary_key=True, serialize=False)),
                ('agreement_number', models.CharField(max_length=20, unique=True)),
                ('signature_date', models.DateTimeField(auto_now_add=True)),
                ('payment_sum', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'rental_agreement',
                'managed': False,
            },
        ),
    ]
